### ISSUE TITLE
窗口大小不应该固定

### ISSUE THREAD

**Issue by DawningW** [ImageBlue/PID_exp_platform#2]
https://github.com/ImageBlue/PID_exp_platform/blob/7a654ca97a826899123f453b0e41e01f893bda63/OController/mainwindow.cpp#L18-L20

最好不要把大小写死, 而是充分利用Qt的布局系统

不写死的原因主要是和分辨率有关, 如果有人还在用640\*480的上古显示器, 那么就没法完全显示750\*500的窗口(虽然不太可能), 所以最好不要写死, 而是能让用户自己调节

**Comment by ImageBlue** [comment]
这么说，4K显示器也很难用
后续会修改这个问题

**Comment by DawningW** [comment]
fixed
